server:
  port: 8081
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    listener:
      client-id: First Listener
      destination: Consumer.myConsumer1.VirtualTopic.MAIN

